vich_uploader:
    db_driver: orm

    mappings:
       Document:
           uri_prefix: /images/Document
           upload_destination: '%kernel.project_dir%/public/images/Document'
           inject_on_load : false
           delete_on_update: true
           delete_on_remove : true